### ISSUE TITLE
change 'Resonite Packages' to '{appName} Packages' ? 

### ISSUE THREAD

**Issue by Muppeq** [Yellow-Dog-Man/Locale#521]
I was just translating the additional committed Resonite name exchanges to {appName} and then found the 'Resonite Packages' in the locale.

Does it make sense to change 'Resonite Packages' to '{appName} Packages' ? 

For example most avatar sellers will still using 'Resonite Package' and not change it to another name. These files come from outside the game. But rebranded Packages could make sense in some other use cases too.

**Comment by stiefeljackal** [comment]
On one hand, it makes sense to replace instances of "Resonite Packages" to "{appName} Packages" since the application name "Resonite" is configurable by business clients. On the other hand, "Resonite Package" is technically a file specification recognized by the engine itself. Additionally, the file type for "Resonite Package" will still remain `.resonitepackage` regardless of the value for `appName`.

**Comment by 5H4D0W-X** [comment]
I think it's not a good idea to change the name of the package especially if the file extension will remain .resonitepackage. Ideally they would be more like generic frooxengine packages without the resonite name, but I feel like it's too late to change that

**Comment by Muppeq** [comment]
One approach to solve this would be to add support for renamed appName packages, so that a rebranded Resonite could use both 'appName Packages' and 'Resonite Packages'.
But then this is no longer a locale issue.

**Comment by Frooxius** [comment]
I don't think this is something we need to worry about right now and just keep it as "Resonite Package", since it's name of the format. There's a few reasons for that:
- Resonite Packages are very customer oriented and the goal is for it to be a recognizable format name
- So far the business use-cases haven't really has much of a need for this feature, particularly in a way that would have their branding - if this comes up, we can do this
- Somewhat related, with whitelabel cases some use "Powered by Resonite" labeling, so the name still works even if they needed it - it makes it more of the "engine/framework" format name
